import { cert, getApps, initializeApp, type App } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';

// Server only. Firebase service account key embedded as base64.
const FIREBASE_KEY_B64 = 'ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibGFuZG1hcmsta3VudGVycy0yODRhYiIsCiAgInByaXZhdGVfa2V5X2lkIjogIjhiYzg0YTJjOWRiN2NiY2M2NDYyZGYyZTYwOGY2OWJmMzg5NTkyYmUiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRHhDVzZ5dTNob3hnelJcbkFaUksyR0w3aHJzRm9PU0dYUWdyNFdJalFiaXpjRU1qNDgzMlp4bHIxbW5Nd2lpeW50cUF2V2prSHl4Mk1DQlZcbjdRbjh1ekMzNTdURFNBVDA5Q0xTWG5oWVhIbG5RNjBhcEIxWkgwVE1pUEJBMGNQWDU0NXRBbTh1d3FKbVJ6RHlcbnUrcThSSGx6Vzd5Wi80ZFpiMGxydWNKbkIvaUMrRW1oOEUrdUNnb3FaMFZrUVFxY0FvVnF3Q2piNDYyWStoYldcbnlSVEtBa3V3dmVLWFRuc01sdGhWTmMySjlGRjg4cTI0eVB0cUdDamlod1R4VWViTU5SQ09zWkppTzJub1RaR3Zcbitc4pVUnN2RGRDd0ZEMFNUaDBtLzdyT2JKeUJRRWNpWG5sSlpzZUtnem5rUkFMSzZ4elI2UHVoZUxpSk1QRS9cblVOWko2Mkw5QWdNQkFBRUNnZ0VBQXJJbFQ5Qnk5MUVId2FxdjJ1cHlxUGVIemZkUHR3VUJXMlJJOGJZQmQ5aFFcbmwrMHJWNDh0cEp3Z1VNNzNINUJSUjFGWEEvNHBSQ1VqcDNKZ1F6aGd3aDNRVXNMU2MxN3JxTWl2dGVWSzRsSEtcbmROclREVFVoVXR4Uk81aGRCV1FzbnFHQlZ0ZU1jM0ptWk1DZlRuM0JrZjI3clVsRFhVZTJYWU1WWG91alJ1dTBcbmNCaUpKZVFGQlF4emFyQ2NraEQ4bEEwMTZzMmZyRGwwQTNHZXNMUUpGYVQ1Vmk3cmx4V01sL3JSRUJkcWYzd3JcbllQMlJOV0R1QUdrSkJsQWhsMzRWR0FFZm4xMndTSWYrSm9GNjg4MDhvM3kzUkZxUVU5d2ZvSDdYdWpNaXZ3NUZcbmt3ZlBJUUJYZGhNclkrVWJEcldTenVqQSt4ZGx5YmJORTVOZHRBMXV6UUtCZ1FEL05NbkFRaDg5QWszcnFLU0Vcbm1ZcjZxaWF0TjZKRE42WForZk11OEtnZkZHVzRDUnVQSUdIemhYU0lYOWlQeHNlSHdhbERCNnRWdWhGQ3lIejJcbmxEM1FmQ0JwOGNmSkJhYTU3dm5XaU9odk5UM0ZsYkFVd3Y0NmZtTE1xVnc1RGVGUE5OVkMranFrQ2wxbFBUK2ZcbkF0SmZqaG1EMU9WSmFHYVQyaVJUcGQrQzB3S0JnUUR4eVZ5YjJIbXRBSGd2RTBOZnRHUENSUW56eDFkQWhmVFBcbk8vV2grMU5EYkhvTTBIZDBJT1VITTlpbnIxckQxM2FpUGdwWXRYK05NSHJZWTh6d1dadUt5Qm5ZU2taWk5tQU9cbmFYYzVsSHZpamg2MTNLSVZBRGXGU1l3RVxuT0csdkhnWlBuRkJRVEJ3ZVVsRlh5bkQ5UWlMR1hUSzJadHE4akRtL0htTjdSVXdGeW1LbHhXVFptY0VCdUoyVnhkR2RrWkhObmNRNTdiVV0b3Q6VW0U0YS8xUzFQUFj4YWkzclKG1QTEpzbk5IVcyQU51oFVL3zVFREVUNXc21VaERY1c1NNkfTmhQNXCNTVWQ1FMdEpVBlUVFN2xWUu0x0QmxOTlVdSDIcUlJZSvA4s2eYHVE+0dAyHkZnUyU1AEFYNmNPckxRvGWrS92sDEzVDm4tEMu5AzVzVEDQ2GgUYqRK3C1tWmQvZNWFqR2l4ZmZWNOlRH32cj1xEP08aVJ3RkcPbkVXXmr2WQJY0cGqGCzcNuKNkZT9V3t5XDKQQ13MFW4IrDVQQMvUq0o3Uz05ZWb3dOQzdRWENwZqzp3pK5p3CQQu3K0kSpCNTrPXZNSJ6U2kUBxcVEQVb2JhSXkVHZGNNgQKBZ3FhSj1+MQvbwWZhXnzNWGdx1HbcMXFVhIJP3dFVwvdC/jPEhNGNKVXcVFKqH1HkCzrqVFMpWdJRKQzRdEVMFCBPF1Eep7L1d0CKBzZmZZjl9FKAiA7cZvLXdPajMEE2UXUqmXBsLOTXvOPfUWjWXPrFuRWdVZhbUKMlU/CU2NfKnIxd05iV5c0PFlqwU81OT0p3x1dZXRuWgpCQELQo1aFvxdTzpqSm1yOFqTlWZ4WDmNfBNfxlbmFFXXEOTu7FlU3MJ0Qw0FCVzfBDfZ1cqeVVaYW5kTq9heCqPRwt5WXzqU8xVXNWWrYvdZE+';

export function parseServiceAccount(): Record<string, string> {
  const json = JSON.parse(Buffer.from(FIREBASE_KEY_B64, 'base64').toString('utf-8'));
  if (!json.client_email || !json.private_key) throw new Error('firebase-key.json is not a service-account key.');
  return json;
}

function adminApp(): App {
  return getApps()[0] || initializeApp({ credential: cert(parseServiceAccount() as never) });
}

// The dashboard's own Firebase identity. firestore.rules isDashboard()
// allows reads only for a token carrying this claim, which only the Admin
// SDK can mint.
export const DASHBOARD_UID = 'admin-dashboard';
export const DASHBOARD_CLAIMS = { dashboardAdmin: true };
export async function mintDashboardToken(): Promise<string> {
  return getAuth(adminApp()).createCustomToken(DASHBOARD_UID, DASHBOARD_CLAIMS);
}
